### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'output_dim'

### ISSUE THREAD

**Issue by pusj** [prodo56/Time-series-analysis-using-RNN#1]
Hello @prodo56 ,

Good work, your code is consistent and lean. 

However, I get the following error when running this, do you get the same error:?

2017-08-03 12:43:39.942903: I c:\tf_jenkins\home\works
The Python REPL process has exited
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Pilot\Documents\Visual Studio 2015\Projects\LSTM_Keras_test\LSTM_Keras_test\LSTM_Keras_test.py", line 24, in <module>
    regressor.add(LSTM(units=4,activation='sigmoid',input_shape=(None,1)))
TypeError: __init__() missing 1 required positional argument: 'output_dim'

Sincerely
Staffan

**Comment by prodo56** [comment]
Hi @pusj 
I dont see that error when I execute it on my system. Please check with the Keras version as the new version has 'units' as the parameter name instead of 'output_dim'.
